# Generated by Django 3.1.4 on 2021-04-06 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_remove_item_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='item_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
